# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e121893b87d0fbaac776d7ed8f7db6314b8803c3afd7f392a8e9a76d8a656c1468f69f0763c17a1e7cf2667e8e8ad289880bf6d284856b24eaa59c7a9d5dd09

test:
  secret_key_base: 584087912f0bdb80f0d23a980d848d83749710bb3746a24fb54c0b0101ef23582a04ac895e7d12cfd10a9faeafcb6ef8b93037865d4eede0979ebc60b52524e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
